name: Build WP image & deploy dev

on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: teamdigitale/dati-semantic-wordpress
  SERVICE_NAME: dati-semantic-wordpress

permissions:
  contents: read
  packages: write

jobs:
  build:
    # Esegue solo se la PR Ã¨ stata merged e sul repository principale
    if: github.event.pull_request.merged == true && github.repository == 'teamdigitale/dati-semantic-wordpress'
    runs-on: ubuntu-latest

    outputs:
      image_name_full: ${{ steps.set_image.outputs.image_name_full }}

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Checkout del repository di contenuto senza if
      - name: Checkout content branch
        uses: actions/checkout@v4
        with:
          repository: istat/wp-schema-deploy
          ref: content
          path: wp-schema-deploy-content
          token: ${{ secrets.WP_SCHEMA_DEPLOY_TOKEN }}
          lfs: true

      - name: Copy .wpress
        run: |
          mkdir -p imported-content
          if [ -d wp-schema-deploy-content ]; then
            cp wp-schema-deploy-content/*.wpress imported-content/ || echo "Nessun .wpress trovato!"
          else
            echo "Repository di contenuto non disponibile, skipping .wpress copy"
          fi

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        id: set_image
        run: |
          IMAGE="$REGISTRY/$IMAGE_NAME"

          echo "Building and pushing Docker image as 'latest'..."
          docker build . --file Dockerfile --tag ${IMAGE}:latest
          docker push ${IMAGE}:latest

          echo "image_name_full=${IMAGE}:latest" >> $GITHUB_OUTPUT

  deploy:
    if: github.event.pull_request.merged == true && github.repository == 'teamdigitale/dati-semantic-wordpress'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Trigger Kubernetes workflow
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: teamdigitale
          repo: dati-semantic-kubernetes
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: update-config.yaml
          ref: dev
          wait_interval: 20
          inputs: >-
            {
              "serviceName": "${{ env.SERVICE_NAME }}",
              "imageWithNewTag": "${{ needs.build.outputs.image_name_full }}"
            }

      - name: Summary
        run: |
          echo "Deploying image: ${{ needs.build.outputs.image_name_full }}"
