name: Build WP image & deploy dev

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: teamdigitale/dati-semantic-wordpress
  SERVICE_NAME: dati-semantic-wordpress

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_name_full: ${{ steps.set_image.outputs.image_name_full }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout content branch
        uses: actions/checkout@v4
        with:
          repository: istat/wp-schema-deploy
          ref: content
          path: wp-schema-deploy-content
          token: ${{ secrets.WP_SCHEMA_DEPLOY_TOKEN }}
          lfs: true

      - name: Copy .wpress
        run: |
          mkdir -p imported-content
          cp wp-schema-deploy-content/*.wpress imported-content/ \
            || { echo "Nessun .wpress trovato!"; exit 1; }

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        id: set_image
        run: |
          IMAGE="$REGISTRY/$IMAGE_NAME"
          TAG="$(date +'%Y%m%d')-${{ github.run_number }}-$(git rev-parse --short HEAD)"

          docker build . --file Dockerfile --tag ${IMAGE}:${TAG}
          docker push ${IMAGE}:${TAG}

          docker tag ${IMAGE}:${TAG} ${IMAGE}:latest
          docker push ${IMAGE}:latest

          echo "image_name_full=${IMAGE}:${TAG}" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Trigger Kubernetes workflow
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: teamdigitale
          repo: dati-semantic-kubernetes
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: update-config.yaml
          ref: dev
          wait_interval: 20
          inputs: >-
            {
              "serviceName": "dati-semantic-wordpress",
              "imageWithNewTag": "${{ needs.build.outputs.image_name_full }}"
            }

      - name: Summary
        run: |
          echo "Deploying image: ${{ needs.build.outputs.image_name_full }}"
          