name: Build WP image & deploy dev

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: teamdigitale/dati-semantic-wordpress
  SERVICE_NAME: dati-semantic-wordpress

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_name_full: ${{ steps.set_image.outputs.image_name_full }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false   # Disabilita Git LFS

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Retrieve files from DB
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER_WP }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD_WP }}
          DB_NAME: ${{ secrets.DB_NAME_WP }}
        run: |
          mkdir -p imported-content/plugins

          # Estrai backup.wpress
          mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD $DB_NAME -e \
            "SELECT FILE FROM sv_ndc_bckwp.test WHERE FILE_NAME='backup.wpress' INTO DUMPFILE 'imported-content/backup.wpress';"

          # Estrai plugin ZIP
          mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD $DB_NAME -e \
            "SELECT FILE FROM sv_ndc_bckwp.test WHERE FILE_NAME='all-in-one-wp-migration-unlimited-extension.zip' INTO DUMPFILE 'imported-content/plugins/all-in-one-wp-migration-unlimited-extension.zip';"

          ls -lh imported-content
          ls -lh imported-content/plugins

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        id: set_image
        run: |
          IMAGE="$REGISTRY/$IMAGE_NAME"
          TAG="$(date +'%Y%m%d')-${{ github.run_number }}-$(git rev-parse --short HEAD)"

          docker build . --file Dockerfile --tag ${IMAGE}:${TAG}
          docker push ${IMAGE}:${TAG}

          docker tag ${IMAGE}:${TAG} ${IMAGE}:latest
          docker push ${IMAGE}:latest

          echo "image_name_full=${IMAGE}:${TAG}" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Trigger Kubernetes workflow
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: teamdigitale
          repo: dati-semantic-kubernetes
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: update-config.yaml
          ref: dev
          wait_interval: 20
          inputs: >-
            {
              "serviceName": "dati-semantic-wordpress",
              "imageWithNewTag": "${{ needs.build.outputs.image_name_full }}"
            }

      - name: Summary
        run: |
          echo "Deploying image: ${{ needs.build.outputs.image_name_full }}"
